version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ddc:latest .
      - docker tag nginx:latest 068896461592.dkr.ecr.us-east-1.amazonaws.com/nginx:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 068896461592.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
