version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...          
      - docker build -t ${REPO_NAME}:latest .
      - docker tag ${REPO_NAME}:latest 068896461592.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest
  post_build:
    commands:
      - echo Build completed on $(date)
      - echo Pushing the Docker image...
      - docker push 068896461592.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest
#      - docker push 068896461592.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest | tee docker-push.out
#      - cat docker-push.out
#      - dockerrun_name=$(sed -n 's/.*digest: \([^ ]*\).*/\1/p' docker-push.out)
#      - echo $dockerrun_name 
#      - aws s3 cp Dockerrun.aws.json s3://fsd-artifacts/$dockerrun_name --acl public-read
#
artifacts:
  files:
    - Dockerrun.aws.json
